language: python
python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
compiler:
  - clang
notifications:
  email: false
before_install:
  - sudo add-apt-repository ppa:staticfloat/julia-deps -y
  - sudo add-apt-repository ppa:staticfloat/julianightlies -y
  - sudo apt-get update -qq -y
  - sudo apt-get install libpcre3-dev julia -y
  - sudo apt-get install python-serial python3-serial -y
script:
  - julia -e 'Pkg.clone(pwd())'
  - julia -e 'Pkg.build("PySerial")'
  - julia --check-bounds=yes -e 'Pkg.test("PySerial")'
